import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LOCALHOST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>

      <main className={styles.main}>
        <h2 className="title">
          <Link href="/bugs">
            <a>All Bugs</a>
          </Link>
        </h2>
        <h2 className="title">
          <Link href="/fish">
            <a>All Fish</a>
          </Link>
        </h2>
      </main>
    </div>
  );
}
