import Head from "next/head";
import Link from "next/link";
import { MonthLink } from "../components/month-link";

export default function Home() {
  const months = [
    { id: 1, name: "January" },
    { id: 2, name: "February" },
    { id: 3, name: "March" },
    { id: 4, name: "April" },
    { id: 5, name: "May" },
    { id: 6, name: "June" },
    { id: 7, name: "July" },
    { id: 8, name: "August" },
    { id: 9, name: "September" },
    { id: 10, name: "October" },
    { id: 11, name: "November" },
    { id: 12, name: "December" },
  ];

  return (
    <div>
      <Head>
        <title>LOCALHOST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>

      <main className="flex items-center justify-center min-h-screen bg-green-200">
        <div className="container mx auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
            <Link href="/bugs">
              <a className="flex justify-center text-4xl border-2 border-yellow-700 rounded-xl p-6 bg-yellow-700 text-yellow-100 my-8">
                All Bugs
              </a>
            </Link>
            <Link href="/fish">
              <a className="flex justify-center text-4xl border-2 border-yellow-700 rounded-xl p-6 bg-yellow-700 text-yellow-100 my-8">
                All Fish
              </a>
            </Link>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-24 gap-y-6">
            {months.map((month) => (
              <>
                <MonthLink month={month.name} />
              </>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
